# Generated by Django 4.1.1 on 2023-02-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('LEE', 'LEE'), ('ALLENSOLLY', 'ALLENSOLLY'), ('APPLE', 'APPLE'), ('SAMSUNG', 'SAMSUNG'), ('REDMI', 'REDMI'), ('ASUS', 'ASUS'), ('DELL', 'DELL'), ('ACER', 'ACER'), ('ONEPLUS', 'ONEPLUS'), ('LG', 'LG'), ('LENOVO', 'LENOVO'), ('NOKIA', 'NOKIA'), ('MOTOROLA', 'MOTOROLA'), ('REALME', 'REALME'), ('WOODLAND', 'WOODLAND'), ('W', 'W'), ('JOCKEY', 'JOCKEY'), ('WILDCRAFT', 'WILDCRAFT')], max_length=15),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MOBILE', 'MOBILE'), ('LAPTOP', 'LAPTOP'), ('TOPWEAR', 'TOPWEAR'), ('BOTTOMWEAR', 'BOTTOMWEAR'), ('SHOES', 'SHOES'), ('WATCH', 'WATCH'), ('HEADPHONE', 'HEADPHONE'), ('APPLIANCE', 'APPLIANCE ')], max_length=10),
        ),
    ]
